version: 0.2

phases:
  install:
    commands:
      - pip install "sagemaker==2.218.0" boto3 pandas joblib

  build:
    commands:
      - echo "Updating SageMaker pipeline..."
      - python src/pipeline.py --update
      - echo "Running SageMaker pipeline..."
      - python src/pipeline.py --run
