version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade sagemaker boto3 scikit-learn

  build:
    commands:
      - python src/pipeline.py --update
      - python src/pipeline.py --run
